# Generated by Django 5.0.7 on 2024-08-03 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.app'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['title'], name='apps_app_title_f1b448_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['user'], name='apps_app_user_id_cfccab_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['is_verified'], name='apps_app_is_veri_cdfd76_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['is_activated'], name='apps_app_is_acti_e37c34_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user'], name='apps_purcha_user_id_6d56e2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['app'], name='apps_purcha_app_id_d471e9_idx'),
        ),
    ]
